#!/bin/bash
# Voice Detection Demo - Command Cheat Sheet
# Quick reference for all common commands

echo "════════════════════════════════════════════════════════════"
echo "🎤 VOICE DETECTION DEMO - COMMAND CHEAT SHEET"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "📦 SETUP COMMANDS"
echo "────────────────────────────────────────────────────────────"
echo "Install dependencies:"
echo "  pip install -r requirements.txt"
echo ""
echo "Validate setup:"
echo "  python validate_setup.py"
echo ""
echo "Quick start (automated):"
echo "  ./quick_start.sh"
echo ""

echo "🎵 AUDIO ACQUISITION"
echo "────────────────────────────────────────────────────────────"
echo "Download sample audio:"
echo "  python download_samples.py"
echo ""
echo "Or use wget:"
echo "  cd test_audio/enrollment"
echo "  wget https://github.com/resemble-ai/Resemblyzer/raw/master/audio_data/1.wav -O sample_1.wav"
echo "  wget https://github.com/resemble-ai/Resemblyzer/raw/master/audio_data/2.wav -O sample_2.wav"
echo "  wget https://github.com/resemble-ai/Resemblyzer/raw/master/audio_data/3.wav -O sample_3.wav"
echo "  cd ../.."
echo ""
echo "Convert audio to WAV:"
echo "  ffmpeg -i input.mp3 -ar 16000 -ac 1 output.wav"
echo ""

echo "🎤 ENROLLMENT COMMANDS"
echo "────────────────────────────────────────────────────────────"
echo "Basic enrollment:"
echo "  python enroll.py test_audio/enrollment/*.wav"
echo ""
echo "With custom output:"
echo "  python enroll.py test_audio/enrollment/*.wav -o my_profile.json"
echo ""
echo "Multiple specific files:"
echo "  python enroll.py sample1.wav sample2.wav sample3.wav -o profile.json"
echo ""
echo "Help:"
echo "  python enroll.py --help"
echo ""

echo "🧪 TESTING COMMANDS"
echo "────────────────────────────────────────────────────────────"
echo "Run full test suite:"
echo "  ./tests/test_phase1-2.sh"
echo ""
echo "Validate profile JSON:"
echo "  python -c \"import json; p=json.load(open('test_profile.json')); print(f'Quality: {p[\\\"quality_score\\\"]:.3f}')\""
echo ""
echo "Check audio files:"
echo "  ls -lh test_audio/enrollment/"
echo ""

echo "🔍 VALIDATION COMMANDS"
echo "────────────────────────────────────────────────────────────"
echo "Check Resemblyzer:"
echo "  python -c 'from resemblyzer import VoiceEncoder; print(\"✅ OK\")'"
echo ""
echo "Check NumPy:"
echo "  python -c 'import numpy; print(\"✅ OK\")'"
echo ""
echo "Check all deps:"
echo "  python validate_setup.py"
echo ""

echo "📊 INSPECTION COMMANDS"
echo "────────────────────────────────────────────────────────────"
echo "View profile summary:"
echo "  python -c \"import json; p=json.load(open('voice_profile.json')); print(f'Samples: {p[\\\"sample_count\\\"]}, Quality: {p[\\\"quality_score\\\"]:.3f}')\""
echo ""
echo "Check embedding dimensions:"
echo "  python -c \"import json; p=json.load(open('voice_profile.json')); print(f'Dimensions: {len(p[\\\"embedding_mean\\\"])}')\""
echo ""
echo "List profile fields:"
echo "  python -c \"import json; print(list(json.load(open('voice_profile.json')).keys()))\""
echo ""

echo "📁 PROJECT STRUCTURE"
echo "────────────────────────────────────────────────────────────"
echo "View file tree:"
echo "  tree -L 2 -I '__pycache__|*.pyc'"
echo ""
echo "List with sizes:"
echo "  ls -lah"
echo ""
echo "Count audio files:"
echo "  ls test_audio/enrollment/*.wav | wc -l"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "────────────────────────────────────────────────────────────"
echo "Reinstall dependencies:"
echo "  pip install --force-reinstall -r requirements.txt"
echo ""
echo "Clear Python cache:"
echo "  find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null"
echo ""
echo "Check Python version:"
echo "  python --version"
echo ""
echo "Test import chain:"
echo "  python -c 'from resemblyzer import VoiceEncoder, preprocess_wav; import numpy as np; print(\"All imports OK\")'"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "For detailed documentation, see:"
echo "  - README.md                   (User guide)"
echo "  - IMPLEMENTATION_SUMMARY.md   (Technical details)"
echo "  - GETTING_STARTED.txt        (Quick reference)"
echo "════════════════════════════════════════════════════════════"
